In [2]:
#!/usr/bin/env python3
import torch
from torch import nn
import numpy as np

In [466]:
class MyNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(1, 2)
        self.output = nn.Linear(2, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.hidden(x)
        x = self.sigmoid(x)
        x = self.output(x)
        return x

x = torch.tensor([[0], [1]], dtype=torch.float32)
d = torch.tensor([[2], [4]], dtype=torch.float32)

sigmoid = nn.Sigmoid()

net = MyNetwork()

v0 = 0
v1 = 4
v2 = -1.0

w11 = 2.0
w10 = 0

w21 = 0.1
w20 = 1.0

# learning rate
eta = 0.1

w = torch.tensor([v0, v1, v2, w10, w20, w11, w21])

net.hidden.weight.data = torch.tensor([[w[5]], [w[6]]])
net.hidden.bias.data = torch.tensor([w[3], w[4]])

net.output.weight.data = torch.tensor([[w[1], w[2]]])
net.output.bias.data = torch.tensor([w[0]])

# Calculate the error
sum = 0
for i in range(x.size()[0]):
    sum = sum + pow((net(x[i]) - d[i]), 2)
E = 0.5*sum

net(x[0]), net(x[1]), E

(tensor([1.2689], grad_fn=<AddBackward0>),
 tensor([2.7729], grad_fn=<AddBackward0>),
 tensor([1.0201], grad_fn=<MulBackward0>))

In [467]:
epochs = 250

for i in range(epochs):    
    # Calculate the gradients
    dE_dv1 = 0;
    sum = 0;
    for i in range(0, 2):
        z1 = sigmoid(x[i]*w11 + w10)
        sum = sum + (net(x[i]) - d[i])*z1
    dE_dv1 = sum

    dE_dv2 = 0;
    sum = 0;
    for i in range(0, 2):
        z2 = sigmoid(x[i]*w21 + w20)
        sum = sum + (net(x[i]) - d[i])*z2
    dE_dv2 = sum

    dE_dv0 = 0;
    sum = 0;
    for i in range(0, 2):
        sum = sum + (net(x[i]) - d[i])
    dE_dv0 = sum

    dE_dw11 = 0;
    sum = 0;
    for i in range(0, 2):
        sum = sum + (net(x[i]) - d[i])*v1*x[i]*sigmoid(x[i]*w11 + w10)*(1-sigmoid(x[i]*w11 + w10))
    dE_dw11 = sum

    dE_dw10 = 0;
    sum = 0;
    for i in range(0, 2):
        sum = sum + (net(x[i]) - d[i])*v1*sigmoid(x[i]*w11 + w10)*(1-sigmoid(x[i]*w11 + w10))
    dE_dw10 = sum

    dE_dw21 = 0;
    sum = 0;
    for i in range(0, 2):
        sum = sum + (net(x[i]) - d[i])*v2*x[i]*sigmoid(x[i]*w21 + w20)*(1-sigmoid(x[i]*w21 + w20))
    dE_dw21 = sum

    dE_dw20 = 0;
    sum = 0;
    for i in range(0, 2):
        sum = sum + (net(x[i]) - d[i])*v2*sigmoid(x[i]*w21 + w20)*(1-sigmoid(x[i]*w21 + w20))
    dE_dw20 = sum

    # Get the Gradient vector
    dE_dw = torch.tensor([dE_dv0, dE_dv1, dE_dv2, dE_dw10, dE_dw20, dE_dw11, dE_dw21])

    # Update the weights
    w = w - eta*dE_dw

    # Update the network
    net.hidden.weight.data = torch.tensor([[w[5]], [w[6]]])
    net.hidden.bias.data = torch.tensor([w[3], w[4]])

    net.output.weight.data = torch.tensor([[w[1], w[2]]])
    net.output.bias.data = torch.tensor([w[0]])

    print(net(x[0]).data, net(x[1]).data, dE_dw, w)

tensor([1.7788]) tensor([3.2868]) tensor([-1.9581, -1.4463, -1.4551, -1.2464,  0.3737, -0.5153,  0.2299]) tensor([ 0.1958,  4.1446, -0.8545,  0.1246,  0.9626,  2.0515,  0.0770])
tensor([2.0193]) tensor([3.5335]) tensor([-0.9345, -0.7388, -0.6968, -0.5208,  0.1771, -0.2995,  0.1336]) tensor([ 0.2893,  4.2185, -0.7848,  0.1767,  0.9449,  2.0815,  0.0636])
tensor([2.1299]) tensor([3.6551]) tensor([-0.4473, -0.4013, -0.3359, -0.1767,  0.0836, -0.1959,  0.0874]) tensor([ 0.3340,  4.2586, -0.7512,  0.1944,  0.9366,  2.1011,  0.0549])
tensor([2.1785]) tensor([3.7174]) tensor([-0.2150, -0.2389, -0.1638, -0.0149,  0.0391, -0.1449,  0.0646]) tensor([ 0.3555,  4.2825, -0.7348,  0.1959,  0.9327,  2.1156,  0.0484])
tensor([2.1974]) tensor([3.7513]) tensor([-0.1042, -0.1597, -0.0816,  0.0598,  0.0179, -0.1187,  0.0530]) tensor([ 0.3659,  4.2985, -0.7267,  0.1899,  0.9309,  2.1274,  0.0431])
tensor([2.2023]) tensor([3.7717]) tensor([-0.0513, -0.1203, -0.0422,  0.0930,  0.0078, -0.1044,  0.0466]) tens